// Copyright (c) 2024 Massachusetts Institute of Technology
// SPDX-License-Identifier: MIT

import CodeMirror from '@uiw/react-codemirror';
import { StreamLanguage } from '@codemirror/language';
import { sparql } from '@codemirror/legacy-modes/mode/sparql';
import { ActionIcon, Button, Checkbox, Modal, Select, TextInput } from "@mantine/core";
import { useContext, useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { IconCaretRight, IconSettings, IconZoomCode } from '@tabler/icons-react';

import { ErrorMessage } from 'components/ErrorMessage';
import { LLMWarning } from 'components/LLMWarning';

import { MainChatAPIContext } from 'hooks/useMainChatAPIInstance';
import { useRunQuery } from 'hooks/useRunQuery';

import { addMessageToSimpleChatHistory, toggleShowFullChatHistory } from 'redux/chatHistorySlice';
import { setBaseURL, setModel } from 'redux/settingsSlice';
import { setQueryValue } from 'redux/queryValueSlice';
import { useAppDispatch, useAppSelector } from 'redux/store';

import { handleUserChat } from 'utils/handleUserChat';
import { tryParsingOutQuery } from 'utils/tryParsingOutQuery';

import styles from "./Chat.module.scss"


export function Chat() {
  const dispatch = useAppDispatch()

  const fullChatHistory = useAppSelector(state => state.chatHistory.fullChatHistory)
  const simpleChatHistory = useAppSelector(state => state.chatHistory.simpleChatHistory)

  const showFullChatHistory = useAppSelector(state => state.chatHistory.showFullChatHistory)

  //based on showFullChatHistory, decide which chat history to display to the user
  const chatHistory = showFullChatHistory ? fullChatHistory : simpleChatHistory

  const chatScrollBottomRef = useRef<HTMLDivElement>(null)
  useEffect(() => {
    if(chatScrollBottomRef.current) {
      chatScrollBottomRef.current.scrollIntoView({ behavior: 'smooth' })
    }
  }, [chatHistory.length])


  // const [inputText, setInputText] = useState<string>("Who won the 2023 Formula One Championship?"); // prefill the chat
  const [inputText, setInputText] = useState<string>("");

  const chatAPI = useContext(MainChatAPIContext)

  const {error, isPending, mutate:submitChat, reset} = useMutation({
    mutationKey: ['submit-chat'],
    /**
     * This function handles what happens when the user submits a chat message
     * It sends the message to the LLM and determines whether to go down the query-building workflow
     * @param text  the user's message
     */
    mutationFn: async (text:string) => {
      //add the user's message to the simple chat history
      dispatch(addMessageToSimpleChatHistory({
        chatId: chatAPI.chatId,
        content: text, 
        name: "user",
        role: "user",
      }))

      const llmResponse = await handleUserChat(text, chatAPI)

      //add the LLM's final response to the simple chat
      dispatch(addMessageToSimpleChatHistory(llmResponse))
    },
    onError(err) {
      console.error(err)
    }
  })

  return (
    <div id={styles["chat-container"]}>
      <Settings/>

      <div id={styles["chat-scroll-container"]}>
        {chatHistory.map((c, i) => {
          return (
            <div key={i} className={`${styles["chat-row"]} ${styles[c.role]}`}>
              <div className={styles["chat-justify"]}>
                {showFullChatHistory && <p>{c.name}, chat #{c.chatId}</p>}
                {
                  c.role === "assistant" 
                  ? <RenderLLMResponse text={c.content} setInputText={setInputText}/>
                  : <pre className={styles.chat}>{c.content}</pre> 
                }
              </div>
            </div>
          )
        })}
        <div ref={chatScrollBottomRef}/>
      </div>

      {error && (
        <Modal opened={true} onClose={reset} title="LLM Error">
          <ErrorMessage>{error.message}</ErrorMessage>
        </Modal>
      )}
      {isPending && <p className={styles.loading}>Loading...</p>}

      <form
        onSubmit={e => {
          e.preventDefault()
          submitChat(inputText)
          setInputText("")
        }}
      >
        <TextInput
          id={styles.input}
          onChange={(event) => setInputText(event.currentTarget.value)}
          placeholder="Chat..."
          size={"md"}
          value={inputText}
        />
      </form>
    </div>
  )
}

function RenderLLMResponse({
  setInputText,
  text,
}:{
  setInputText: (inputText:string) => void,
  text: string,
}) {
  const parsedQuery = tryParsingOutQuery(text)
  if(parsedQuery) {
    return (
      <div className={styles.chat}>
        <LLMWarning>
          <p>This was generated by an LLM that can make mistakes.</p>
        </LLMWarning>

        <RenderSparqlQuery
          pre={parsedQuery.pre}
          query={parsedQuery.query.trim()}
          post={parsedQuery.post}

          setInputText={setInputText}
        />
      </div>
    )
  }

  return (
    <div className={styles.chat}>
      <LLMWarning>
        <p>This was generated by an LLM that can make mistakes.</p>
      </LLMWarning>
      
      <pre>{text}</pre>
    </div>
  )
}



function RenderSparqlQuery({
  pre,
  query,
  post,

  setInputText,
}:{
  pre: string,
  query: string,
  post: string,

  setInputText: (inputText:string) => void,
}) {
  const dispatch = useAppDispatch()

  const { runQuery } = useRunQuery()

  return (
    <>
      <pre>{pre}</pre>
      <CodeMirror
        extensions={[StreamLanguage.define(sparql)]}
        value={query}
      />
      <div className={styles["copy-query-buttons"]}>
        <div>
          <Button onClick={() => dispatch(setQueryValue(query))} variant="outline" color="white">Copy query over to examine <IconZoomCode/></Button>
          <br/>
          <Button onClick={() => {
            dispatch(setQueryValue(query))
            runQuery(query)
          }}>Copy query over and run <IconCaretRight/></Button>
        </div>
      </div>
      <pre>{post}</pre>
      <br/>
      <Button onClick={() => setInputText("You identified the wrong data. I was actually looking for: ")} style={{marginTop:"0.5rem"}}>You identified the wrong data</Button>
      <br/>
      <Button onClick={() => setInputText("You misunderstood my question. I was actually asking about: ")} style={{marginTop:"0.5rem"}}>You misunderstood my question</Button>
      <br/>
      <Button onClick={() => setInputText("I want to ask something different: ")}>I want to ask something different</Button>
    </>
  )
}



function Settings() {
  const dispatch = useAppDispatch()

  const baseURL = useAppSelector(state => state.settings.baseURL)
  const model = useAppSelector(state => state.settings.model)
  const showFullChatHistory = useAppSelector(state => state.chatHistory.showFullChatHistory)

  const [showSettingsModal, setShowSettingsModal] = useState<boolean>(false)
  const closeSettingsModal = () => setShowSettingsModal(false)
  
  const chatAPI = useContext(MainChatAPIContext)

  const {data, error, isLoading} = useQuery({
    queryKey: [baseURL],
    queryFn: async () => {
      //https://platform.openai.com/docs/api-reference/models/list
      const list = await chatAPI.openAI.models.list()
      return list.data.map(({id}) => id).sort()
    },
  })
  useEffect(() => {
    //if the model chosen is no longer in the list
    if(data && !data.includes(model) && data[0]) {
      //auto-pick the first option
      dispatch(setModel(data[0]))
    }
  }, [data])

  return (
    <>
      <Modal opened={showSettingsModal} onClose={closeSettingsModal} title="Settings">
        <Checkbox
          checked={showFullChatHistory}
          onChange={() => dispatch(toggleShowFullChatHistory())}
          label="Show full chat history"
        />
        <hr/>
        <TextInput
          label="LLM Base URL"
          description="Base URL to make chat completion requests to"
          placeholder="Ex: https://api.openai.com/v1/"
          value={baseURL}
          onChange={(event) => dispatch(setBaseURL(event.currentTarget.value))}
        />
        <br/>
        {isLoading ? <p>Loading models...</p> : (
          <>
            <Select
              label="Model"
              placeholder="Choose your model"
              data={data}
              value={model}
              onChange={(value) => value && dispatch(setModel(value))}
            />
            {error && <ErrorMessage>{error.message}</ErrorMessage>}
          </>
        )}
        
      </Modal>

      <ActionIcon id={styles["chat-settings-button"]} size="sm" variant="filled" aria-label="Show Settings" onClick={() => setShowSettingsModal(true)}>
        <IconSettings/>
      </ActionIcon>
    </>
  )
}